WebApplication2/WebApplication2/Models/GopY.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace WebApplication2.Models
{
    public class GopY
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [DisplayName("Tên khách hàng")]
        [Required(ErrorMessage = "Xin nhập tên")]
        public string tenKH { get; set; }

        [DisplayName("Email")]
        [Required(ErrorMessage = "Xin nhập email")]
        public string email { get; set; }

        [DisplayName("Tiêu đề")]
        [Required(ErrorMessage = "Xin nhập tiêu đề")]
        public string tieuDe { get; set; }

        [DisplayName("Nội dung")]
        [Required(ErrorMessage = "Xin nhập nội dung")]
        public string noiDung { get; set; }
    }
}

WebApplication2/WebApplication2/Controllers/HomeController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class HomeController : Controller
    {
        private DataContext db = new DataContext();

        public Boolean isAdminUser()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = User.Identity;
                ApplicationDbContext context = new ApplicationDbContext();
                var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));
                var s = UserManager.GetRoles(user.GetUserId());
                if (s[0].ToString() == "Admin")
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            return false;
        }

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult About()
        {
            return View();
        }
        public ActionResult GopY()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GopY([Bind(Include = "id,tenKH,email,tieuDe,noiDung")] GopY gopY)
        {
            if (ModelState.IsValid)
            {
                db.GopYs.Add(gopY);
                db.SaveChanges();
            }

            return View(gopY);
        }

        [Authorize]
        public ActionResult ListTour(string ten)
        {
            var tim = from a in db.Tours select a;
            if (!String.IsNullOrEmpty(ten))
            {
                tim = tim.Where(s => s.tenTour.Contains(ten)); 
            }
            return View(tim);
            //return View(db.Tours.ToList());
        }

        public ActionResult CTTour(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tour tour = db.Tours.Find(id);
            if (tour == null)
            {
                return HttpNotFound();
            }
            return View(tour);
        }

        //public ActionResult HoaDon()
        //{
        //    return View();
        //}
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult HoaDon([Bind(Include = "id,soKhach,giaTien")] HoaDon hoaDon)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.HoaDons.Add(hoaDon);
        //        db.SaveChanges();
        //    }

        //    return View(hoaDon);
        //}
        public ActionResult QuanLi()
        {
            return View();
        }
    }
}

WebApplication2/WebApplication2/Controllers/TaiKhoanController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class TaiKhoanController : Controller
    {
        ApplicationDbContext context = new ApplicationDbContext();

        public ActionResult UsersWithRoles()
        {
            var usersWithRoles = (from user in context.Users
                                  select new
                                  {
                                      UserId = user.Id,
                                      Username = user.UserName,
                                      Email = user.Email,
                                      RoleNames = (from userRole in user.Roles
                                                   join role in context.Roles on userRole.RoleId
                                                   equals role.Id
                                                   select role.Name).ToList()
                                  }).ToList().Select(p => new UserWithRole()

                                  {
                                      UserId = p.UserId,
                                      Username = p.Username,
                                      Email = p.Email,
                                      Role = string.Join(",", p.RoleNames)
                                  });


            return View(usersWithRoles);
        }
    }


}

WebApplication2/WebApplication2/Controllers/ToursController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class ToursController : Controller
    {
        private DataContext db = new DataContext();

        // GET: Tours
        public ActionResult Index()
        {
            return View(db.Tours.ToList());
        }

        // GET: Tours/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tour tour = db.Tours.Find(id);
            if (tour == null)
            {
                return HttpNotFound();
            }
            return View(tour);
        }

        // GET: Tours/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Tours/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,tenTour,thoiGian,phuongTien,gia,ngayDi,chiTiet")] Tour tour)
        {
            if (ModelState.IsValid)
            {
                db.Tours.Add(tour);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tour);
        }

        // GET: Tours/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tour tour = db.Tours.Find(id);
            if (tour == null)
            {
                return HttpNotFound();
            }
            return View(tour);
        }

        // POST: Tours/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,tenTour,thoiGian,phuongTien,gia,ngayDi,chiTiet")] Tour tour)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tour).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tour);
        }

        // GET: Tours/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tour tour = db.Tours.Find(id);
            if (tour == null)
            {
                return HttpNotFound();
            }
            return View(tour);
        }

        // POST: Tours/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tour tour = db.Tours.Find(id);
            db.Tours.Remove(tour);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication2/WebApplication2/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="site-blocks-cover inner-page-cover" style="background-image: url(../../Resource/images/hero_bg_2.jpg);" data-aos="fade" data-stellar-background-ratio="0.5">
    <div class="container">
        <div class="row align-items-center justify-content-center text-center">
            <div class="col-md-8" data-aos="fade-up" data-aos-delay="400">
                <h1 class="text-white font-weight-light">About Travelers</h1>
                <div>@Html.ActionLink("Home", "Index", "Home") <span class="mx-2 text-white">&bullet;</span> <span class="text-white">About</span></div>

            </div>
        </div>
    </div>
</div>


<div class="site-section" data-aos="fade-up">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-6 mb-5 mb-md-0">
                <img src="~/Resource/images/hero_bg_2.jpg" alt="Image" class="img-fluid rounded">
            </div>
            <div class="col-md-6 pl-md-5">
                <h2 class="font-weight-light text-black mb-4">About Company</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vitae cumque eius modi expedita accusamus alias error totam ab magnam a mollitia magni, distinctio temporibus optio illo sapiente, odio unde natus.</p>
                <ul class="list-unstyled">
                    <li class="d-flex align-items-center"><span class="icon-check2 text-primary h3 mr-2"></span><span>Vitae cumque eius modi expedita</span></li>
                    <li class="d-flex align-items-center"><span class="icon-check2 text-primary h3 mr-2"></span><span>Totam at maxime Accusantium</span></li>
                    <li class="d-flex align-items-center"><span class="icon-check2 text-primary h3 mr-2"></span><span>Distinctio temporibus</span></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="site-section">
    <div class="container">
        <div class="row justify-content-center mb-5" data-aos="fade-up">
            <div class="col-md-7">
                <h2 class="font-weight-light text-black text-center">Our Team</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-lg-4 text-center mb-5" data-aos="fade-up">
                <img src="~/Resource/images/person_1.jpg" alt="Image" class="img-fluid w-50 rounded-circle mb-4">
                <h2 class="text-black font-weight-light mb-4">Jean McMiller</h2>
                <p class="mb-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur ab quas facilis obcaecati non ea, est odit repellat distinctio incidunt, quia aliquam eveniet quod deleniti impedit sapiente atque tenetur porro?</p>
                <p>
                    <a href="#" class="pl-0 pr-3"><span class="icon-twitter"></span></a>
                    <a href="#" class="pl-3 pr-3"><span class="icon-instagram"></span></a>
                    <a href="#" class="pl-3 pr-3"><span class="icon-facebook"></span></a>
                </p>
            </div>
            <div class="col-md-6 col-lg-4 text-center mb-5" data-aos="fade-up">
                <img src="~/Resource/images/person_2.jpg" alt="Image" class="img-fluid w-50 rounded-circle mb-4">
                <h2 class="text-black font-weight-light mb-4">Claire Peters</h2>
                <p class="mb-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur ab quas facilis obcaecati non ea, est odit repellat distinctio incidunt, quia aliquam eveniet quod deleniti impedit sapiente atque tenetur porro?</p>
                <p>
                    <a href="#" class="pl-0 pr-3"><span class="icon-twitter"></span></a>
                    <a href="#" class="pl-3 pr-3"><span class="icon-instagram"></span></a>
                    <a href="#" class="pl-3 pr-3"><span class="icon-facebook"></span></a>
                </p>
            </div>
            <div class="col-md-6 col-lg-4 text-center mb-5" data-aos="fade-up">
                <img src="~/Resource/images/person_4.jpg" alt="Image" class="img-fluid w-50 rounded-circle mb-4">
                <h2 class="text-black font-weight-light mb-4">John Sawyer</h2>
                <p class="mb-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur ab quas facilis obcaecati non ea, est odit repellat distinctio incidunt, quia aliquam eveniet quod deleniti impedit sapiente atque tenetur porro?</p>
                <p>
                    <a href="#" class="pl-0 pr-3"><span class="icon-twitter"></span></a>
                    <a href="#" class="pl-3 pr-3"><span class="icon-instagram"></span></a>
                    <a href="#" class="pl-3 pr-3"><span class="icon-facebook"></span></a>
                </p>
            </div>
        </div>
    </div>
</div>
<div class="site-section block-13 bg-light">

    <div class="container" data-aos="fade">
        <div class="row justify-content-center mb-5">
            <div class="col-md-7">
                <h2 class="font-weight-light text-black text-center">What People Says</h2>
            </div>
        </div>
        <div class="nonloop-block-13 owl-carousel">
            <div class="item">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-6 mb-5">
                            <img src="~/Resource/images/img_1.jpg" alt="Image" class="img-md-fluid">
                        </div>
                        <div class="overlap-left col-lg-6 bg-white p-md-5 align-self-center">
                            <p class="text-black lead">&ldquo;Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique dolorem quisquam laudantium, incidunt id laborum, tempora aliquid labore minus. Nemo maxime, veniam! Fugiat odio nam eveniet ipsam atque, corrupti porro&rdquo;</p>
                            <p class="">&mdash; <em>James Martin</em>, <a href="#">Traveler</a></p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-6 mb-5">
                            <img src="~/Resource/images/img_2.jpg" alt="Image" class="img-md-fluid">
                        </div>
                        <div class="overlap-left col-lg-6 bg-white p-md-5 align-self-center">
                            <p class="text-black lead">&ldquo;Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique dolorem quisquam laudantium, incidunt id laborum, tempora aliquid labore minus. Nemo maxime, veniam! Fugiat odio nam eveniet ipsam atque, corrupti porro&rdquo;</p>
                            <p class="">&mdash; <em>Clair Augustin</em>, <a href="#">Traveler</a></p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-6 mb-5">
                            <img src="~/Resource/images/img_4.jpg" alt="Image" class="img-md-fluid">
                        </div>
                        <div class="overlap-left col-lg-6 bg-white p-md-5 align-self-center">
                            <p class="text-black lead">&ldquo;Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique dolorem quisquam laudantium, incidunt id laborum, tempora aliquid labore minus. Nemo maxime, veniam! Fugiat odio nam eveniet ipsam atque, corrupti porro&rdquo;</p>
                            <p class="">&mdash; <em>James Martin</em>, <a href="#">Traveler</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="site-section border-top">
    <div class="container">
        <div class="row text-center">
            <div class="col-md-12">
                <h2 class="mb-5 text-black">Want To Travel With Us?</h2>
                <p class="mb-0"><a href="booking.html" class="btn btn-primary py-3 px-5 text-white">Book Now</a></p>
            </div>
        </div>
    </div>
</div>

WebApplication2/WebApplication2/Views/Home/CTTour.cshtml
@model WebApplication2.Models.Tour

@{
    ViewBag.Title = "CTTour";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CHI TIẾT TOUR</h2>

<div class="site-section" data-aos="fade-up">
	<div class="container">
		<div class="row align-items-center">
			<div class="col-md-6 mb-5 mb-md-0">
                <img src="~/Resource/images/hero_bg_2.jpg" alt="Image" class="img-fluid rounded">
            </div>
			<div class="col-md-6 pl-md-5">
						<h2 class="font-weight-light text-black mb-4 ">Thông tin tour du lịch</h2>
						<p>Ha Long Bay là môt danh lam thắng cảnh ở Viêt Nam và là môt vinh thuôc Bắc bộ.</p>
						<hr>

					<ul class="list-unstyled">					
        				<h2>
						<li class="d-flex align-items-center"></tab>
							@Html.DisplayFor(model => model.tenTour)
						</li>
						</h2>

						<li class="d-flex align-items-center" >
							@Html.DisplayNameFor(model => model.thoiGian)
						</li>

						<li class="d-flex align-items-center">
							@Html.DisplayFor(model => model.thoiGian)
						</li>

						<li class="d-flex align-items-center">
							@Html.DisplayNameFor(model => model.phuongTien)
						</li>

						<li class="d-flex align-items-center">
							@Html.DisplayFor(model => model.phuongTien)
						</li>

						<li class="d-flex align-items-center">
							@Html.DisplayNameFor(model => model.gia)
						</li>

						<li class="d-flex align-items-center">
							@Html.DisplayFor(model => model.gia)
						</li>

						<li class="d-flex align-items-center">
							@Html.DisplayNameFor(model => model.ngayDi)
						</li>

						<li class="d-flex align-items-center">
							@Html.DisplayFor(model => model.ngayDi)
						</li>

						<li class="d-flex align-items-center">
							@Html.DisplayNameFor(model => model.chiTiet)
						</li>

						<li class="d-flex align-items-center">
							@Html.DisplayFor(model => model.chiTiet)
						</li>
				</ul>
                    <p>
                        @Html.ActionLink("Đặt tour", "DatTour", "Home", new { id = Model.Id, @class = "btn btn-primary py-1 px-3 text-white" }) &nbsp &nbsp
                        @if (User.IsInRole("Admin"))
                        {
                            @Html.ActionLink("Sửa", "Edit", "Tours", new { id = Model.Id }, null)
                        }
                    </p> 
		</div>
	</div>
</div>
<p>
    
    @Html.ActionLink("Back to List", "ListTour")
</p>

WebApplication2/WebApplication2/Views/Home/EditTour.cshtml
@model WebApplication2.Models.Tour

@{
    ViewBag.Title = "EditTour";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>EditTour</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tour</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.tenTour, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tenTour, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tenTour, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.thoiGian, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.thoiGian, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.thoiGian, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phuongTien, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phuongTien, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phuongTien, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.gia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.gia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.gia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ngayDi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ngayDi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ngayDi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.chiTiet, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.chiTiet, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.chiTiet, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApplication2/WebApplication2/Views/Home/GopY.cshtml
@model WebApplication2.Models.GopY

@{
                /**/

                ViewBag.Title = "GopY";
                Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="site-blocks-cover inner-page-cover" style="background-image: url(../../Resource/images/hero_bg_2.jpg);" data-aos="fade" data-stellar-background-ratio="0.5">
    <div class="container">
        <div class="row align-items-center justify-content-center text-center">
            <div class="col-md-8" data-aos="fade-up" data-aos-delay="400">
                <h1 class="text-white font-weight-light">Get In Touch</h1>
                <div>@Html.ActionLink("Home", "Index", "Home")</a> <span class="mx-2 text-white">&bullet;</span> <span class="text-white">Góp ý</span></div>
            </div>
        </div>
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="site-section bg-light">
        <div class="container">
            <div class="row">
                <div class="col-md-7 mb-5">

                    <form action="#" class="p-5 bg-white">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="row form-group">
                            @Html.LabelFor(model => model.tenKH, htmlAttributes: new { @class = "control-label col-md-12" })
                            <div class="col-md-12">
                                @Html.EditorFor(model => model.tenKH, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.tenKH, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="row form-group">
                            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-12" })
                            <div class="col-md-12">
                                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="row form-group">
                            @Html.LabelFor(model => model.tieuDe, htmlAttributes: new { @class = "control-label col-md-12" })
                            <div class="col-md-12">
                                @Html.EditorFor(model => model.tieuDe, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.tieuDe, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="row form-group">
                            @Html.LabelFor(model => model.noiDung, htmlAttributes: new { @class = "control-label col-md-12" })
                            <div class="col-md-12">
                                @Html.TextAreaFor(model => model.noiDung, htmlAttributes: new { style = "width: 100%; max-width: 100%; height:150px" })
                                @Html.ValidationMessageFor(model => model.noiDung, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="row form-group">
                            <div class="col-md-12">
                                <input type="submit" value="Góp ý" class="btn btn-primary py-2 px-4 text-white">
                            </div>
                        </div>

                    </form>
                </div>
                <div class="col-md-5">

                    <div class="p-4 mb-3 bg-white">
                        <p class="mb-0 font-weight-bold">Address</p>
                        <p class="mb-4">203 Fake St. Mountain View, San Francisco, California, USA</p>
                        <p class="mb-0 font-weight-bold">Phone</p>
                        <p class="mb-4"><a href="#">+1 232 3235 324</a></p>
                        <p class="mb-0 font-weight-bold">Email Address</p>
                        <p class="mb-0"><a href="#">youremail@domain.com</a></p>
                    </div>

                    <div class="p-4 mb-3 bg-white">
                        <img src="~/Resource/images/hero_bg_1.jpg" alt="Image" class="img-fluid mb-4 rounded">
                        <h3 class="h5 text-black mb-3">More Info</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa ad iure porro mollitia architecto hic consequuntur. Distinctio nisi perferendis dolore, ipsa consectetur? Fugiat quaerat eos qui, libero neque sed nulla.</p>
                        <p><a href="#" class="btn btn-primary px-4 py-2 text-white">Learn More</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

WebApplication2/WebApplication2/Views/Home/QuanLi.cshtml
@{
    ViewBag.Title = "QuanLi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<p>@Html.ActionLink("Quản lí tài khoản", "Index", "TaiKhoan")</p>
<p>@Html.ActionLink("Quản lí tour", "Index", "Tours")</p>
<p>@Html.ActionLink("Quản lí hóa đơn", "Index", "HoaDon")</p>